# For details see:
# https://gitlab.invenia.ca/invenia/gitlab-ci-helper/-/blob/master/examples/julia.yml
---
include:
  - project: invenia/gitlab-ci-helper
    file: /templates/julia.yml

variables:
  GKSwstype: "100"    # Needed for documenter plots in headless mode https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988/2?u=rory-finnegan
  julia: "1.6, 1.8"  # TODO: Remove once default version switches to 1.8

# If you need to install system packages, such as `unzip`, you can do so as follows:
# .test:
#  before_script:
#    - echo "$ci_init" > ci_init && source ci_init && rm ci_init
#    - package_install libomp
